# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noms', models.CharField(help_text='Els cantants que van a triomfar', max_length=200)),
                ('link', models.CharField(help_text='Link al YouTube, Vimeo o altres', max_length=300)),
                ('comentari', models.TextField(blank=True)),
            ],
        ),
    ]
