# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 13:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 20, 13, 56, 18, 164250)),
        ),
    ]
