# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 13:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke', '0002_item_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='link',
        ),
        migrations.AddField(
            model_name='item',
            name='url',
            field=models.URLField(default='', help_text='Link al YouTube, Vimeo o altres', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 20, 13, 59, 11, 37178)),
        ),
    ]
