# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-20 15:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke', '0003_auto_20161220_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='fet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='tema',
            field=models.CharField(default='tema', help_text='Tema que cantareu', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 20, 15, 12, 19, 31221)),
        ),
    ]
